[env]
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600
lib_deps      = h2zero/NimBLE-Arduino @ ^1.4.3
build_flags   = -DCORE_DEBUG_LEVEL=3

[env:c3]
platform  = espressif32
board     = esp32-c3-devkitm-1
build_flags = ${env.build_flags} -DTARGET_C3
; C3 SuperMini — native USB CDC, shows up as /dev/ttyACMx
monitor_port = /dev/ttyACM0

[env:s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
build_flags = ${env.build_flags} -DTARGET_S3
; S3 DevKitC-1 UART port (via CP2102) — /dev/ttyUSBx
; If using native USB port instead: /dev/ttyACM0
monitor_port = /dev/ttyUSB0
